export enum ErrorCodeEnum {
  PERMISSION_DENIED = 403,
  UNAUTHORIZED = 600,
  EMAIL_ALREADY_EXISTS = 601,
  PHONE_ALREADY_EXISTS = 602,
  INVALID_CREDENTIALS = 603,
  BLOCKED_USER = 604,
  USER_DOES_NOT_EXIST = 605,
  ITEM_NOT_EXIST = 607,
  SAME_SECURITY_GROUP = 608,
  CAN_NOT_DELETE_SUPER_ADMIN_GROUP = 609,
  SECURITY_GROUP_NOT_EXIST = 610,
  CART_ITEM_NOT_EXIST = 611,
  CART_ITEM_NOT_BELONGS_TO_USER = 612
}
