export enum ErrorCodeEnum {
  PERMISSION_DENIED = 403,
  UNAUTHORIZED = 600,
  EMAIL_ALREADY_EXISTS = 601,
  PHONE_ALREADY_EXISTS = 602,
  INVALID_CREDENTIALS = 603,
  BLOCKED_USER = 604,
  USER_DOES_NOT_EXIST = 605
}
